export default {
  index: '导读',
  introduction: '简介与心智模型',
  tooling: '工具链',
  sfc: '单文件组件',
  'template-syntax': '模板语法与插值',
  directives: '指令系统',
  components: '组件注册与通信',
  'props-events': 'Props、Events、v-model',
  rendering: '渲染机制',
  'computed-watchers': '计算属性与侦听器',
  'api-styles': 'API 风格',
  lifecycle: '生命周期钩子',
  'event-handling': '事件处理',
  forms: '表单处理',
  advanced: '高级特性',
  'directives-plugins': '自定义指令与插件',
  slots: '插槽系统',
  animation: '动画与过渡',
  routing: '路由',
  'state-management': '状态管理',
  styling: '样式方案',
  'api-calls': '数据请求',
  'forms-validation': '表单库与校验',
  testing: '测试',
  'ssr-ssg': 'SSR/SSG',
  mobile: '移动端'
}
