export default {
  index: '导读',
  introduction: '简介与心智模型',
  'dart-basics': 'Dart 基础',
  'dart-oop': 'Dart 类系统',
  'dart-functional': 'Dart 集合与函数式',
  'dart-async': 'Dart 异步与并发',
  tooling: '工具链',
  'widgets-basics': 'Widgets 基础',
  'widgets-material': 'Material 3 与 Cupertino',
  'layout-styling': '布局、约束与主题',
  rendering: '渲染机制',
  navigation: '路由与导航',
  'state-management': '状态管理',
  reactive: '响应式编程',
  networking: '数据请求',
  storage: '持久化',
  firebase: 'Firebase 与 BaaS',
  forms: '表单与校验',
  animation: '动画',
  'design-principles': '设计原则与架构',
  testing: '测试',
  'devtools-perf': '调试与性能',
  'ci-cd-deploy': 'CI/CD 与发布',
  analytics: '埋点与监控',
  'platform-integration': '平台集成'
}
