export default {
  index: '首页',
  introduction: '简介与优势',
  'getting-started': '快速起步',
  'app-router-vs-pages': 'App Router vs Pages Router',
  'project-structure': '项目结构',
  configuration: '配置体系',
  'routing-basics': '路由基础',
  'dynamic-routes': '动态路由',
  'route-groups-layouts': '路由组与布局',
  'templates-loading-error': '模板、加载与错误处理',
  'linking-navigation': '链接与导航',
  'parallel-intercepting-routes': '并行与拦截路由',
  middleware: '中间件',
  'server-client-components': '服务端与客户端组件',
  'server-side-rendering': '服务端渲染策略',
  'isr-ppr': 'ISR 与局部预渲染',
  'streaming-suspense': '流式渲染与 Suspense',
  caching: '缓存体系',
  'data-fetching': '数据获取',
  'server-actions': 'Server Actions',
  'route-handlers': 'Route Handlers',
  database: '数据库集成',
  authentication: '身份认证',
  styling: '样式方案',
  'images-fonts': '图片与字体优化',
  'scripts-assets': '脚本与静态资源',
  performance: '性能优化',
  'metadata-seo': 'Metadata 与 SEO',
  deployment: '部署',
  testing: '测试',
  'patterns-best-practices': '模式与最佳实践',
}
