export default {
  index: '导读',
  introduction: '简介与优势',
  'typescript-vs-javascript': 'TypeScript vs JavaScript',
  setup: '安装与配置',
  tsconfig: 'tsconfig.json 详解',
  'basic-types': '基本类型',
  'object-types': '对象类型',
  'type-inference': '类型推断',
  'type-compatibility': '类型兼容性',
  'union-intersection': '联合与交叉类型',
  'type-aliases': '类型别名',
  'type-guards': '类型守卫与收窄',
  interfaces: '接口',
  classes: '类',
  generics: '泛型',
  functions: '函数类型',
  'utility-types-1': '工具类型（上）',
  'utility-types-2': '工具类型（下）',
  'mapped-types': '映射类型',
  'conditional-types': '条件类型',
  'template-literal-types': '模板字面量类型',
  decorators: '装饰器',
  modules: '模块系统',
  namespaces: '命名空间',
  'react-typescript': 'React + TypeScript 基础',
  'react-hooks-typescript': 'React Hooks 类型',
  'react-components-typescript': 'React 组件模式',
  'react-patterns': 'React 高级类型',
  ecosystem: '生态系统工具',
  'best-practices': '最佳实践',
  'real-world': '实战案例'
}
